name: 'Build Koda'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["oddrocket/koda"]'
      alphas: '["qwerty"]'
      mapping: '["EXTENDED_THUMBS"]'
